# Generated by Django 5.0.1 on 2026-05-05 23:23

import apps.utils.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('note', models.TextField(help_text='Contenido de la nota', verbose_name='Nota')),
                ('is_important', models.BooleanField(default=False, help_text='Marcar como importante', verbose_name='¿Es importante?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación', verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización', verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Nota de Llamada',
                'verbose_name_plural': 'Notas de Llamadas',
                'db_table': 'pipeline_call_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('fecha', models.DateField(db_index=True, help_text='Fecha de las llamadas')),
                ('telefono', models.CharField(db_index=True, help_text='Número telefónico que realizó llamadas', max_length=20, validators=[apps.utils.validators.validate_phone_number])),
                ('servicio_800', models.CharField(db_index=True, help_text='Número servicio 800 destino', max_length=20, validators=[apps.utils.validators.validate_service_800])),
                ('total_llamadas', models.IntegerField(default=0, help_text='Total de llamadas realizadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('llamadas_contestadas', models.IntegerField(default=0, help_text='Llamadas contestadas por agente', validators=[django.core.validators.MinValueValidator(0)])),
                ('llamadas_abandonadas', models.IntegerField(default=0, help_text='Llamadas abandonadas (colgadas antes de contestar)', validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_total_segundos', models.IntegerField(default=0, help_text='Duración total en segundos', validators=[django.core.validators.MinValueValidator(0)])),
                ('call_type', models.CharField(choices=[('INBOUND', 'Entrante'), ('OUTBOUND', 'Saliente'), ('INTERNAL', 'Interna'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', help_text='Tipo de llamada', max_length=20, verbose_name='Tipo de llamada')),
                ('recording_path', models.CharField(blank=True, help_text='Ruta de archivo de grabación (si existe)', max_length=255, null=True, verbose_name='Ruta grabación')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp creación registro')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp última actualización')),
            ],
            options={
                'verbose_name': 'Registro de Llamada',
                'verbose_name_plural': 'Registros de Llamadas',
                'db_table': 'core_call_records',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('nombre', models.CharField(help_text='Nombre del centro de atención', max_length=200)),
                ('codigo', models.CharField(db_index=True, help_text='Código único del centro (ej: CT01, CENTER_SCL)', max_length=20, unique=True, validators=[apps.utils.validators.validate_codigo_center])),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del centro')),
                ('direccion', models.CharField(blank=True, help_text='Dirección física del centro', max_length=500)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Centro actualmente operativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
            ],
            options={
                'verbose_name': 'Centro',
                'verbose_name_plural': 'Centros',
                'db_table': 'core_centers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ETLExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'Ejecutando'), ('SUCCESS', 'Exitoso'), ('FAILED', 'Fallido')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('records_extracted', models.IntegerField(default=0, help_text='Cantidad de registros extraidos de IVR', verbose_name='Registros extraidos')),
                ('records_loaded', models.IntegerField(default=0, help_text='Cantidad de registros cargados en Analytics', verbose_name='Registros cargados')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
            ],
            options={
                'verbose_name': 'Ejecucion ETL',
                'verbose_name_plural': 'Ejecuciones ETL',
                'db_table': 'etl_executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('numero_800', models.CharField(db_index=True, help_text='Número servicio 800 (ej: 800-123-4567)', max_length=20, unique=True, validators=[apps.utils.validators.validate_service_800])),
                ('nombre', models.CharField(help_text='Nombre del servicio', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del servicio')),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='¿Servicio actualmente operativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'core_services',
                'ordering': ['numero_800'],
            },
        ),
    ]
