# Generated by Django 5.0.1 on 2026-01-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="callnote",
            name="user",
            field=models.ForeignKey(
                help_text="Usuario que creó la nota",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pipeline_call_notes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Agente que atendió la llamada (si aplica)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_records_as_agent",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agente",
            ),
        ),
        migrations.AddField(
            model_name="callnote",
            name="call_record",
            field=models.ForeignKey(
                help_text="Registro de llamada asociado",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="pipeline.callrecord",
                verbose_name="Registro de llamada",
            ),
        ),
        migrations.AddIndex(
            model_name="center",
            index=models.Index(
                fields=["activo", "codigo"], name="core_center_activo_613c4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlexecution",
            index=models.Index(
                fields=["-started_at"], name="etl_executi_started_30cb87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="etlexecution",
            index=models.Index(
                fields=["status", "-started_at"], name="etl_executi_status_e374a8_idx"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="center",
            field=models.ForeignKey(
                help_text="Centro al que pertenece el servicio",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="services",
                to="pipeline.center",
            ),
        ),
        migrations.AddField(
            model_name="callrecord",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="Servicio asociado (si existe en tabla Service)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="call_records",
                to="pipeline.service",
                verbose_name="Servicio",
            ),
        ),
        migrations.AddIndex(
            model_name="callnote",
            index=models.Index(
                fields=["call_record", "-created_at"],
                name="pipeline_ca_call_re_ac6c6b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callnote",
            index=models.Index(
                fields=["user", "-created_at"], name="pipeline_ca_user_id_10566c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callnote",
            index=models.Index(
                fields=["is_important", "-created_at"],
                name="pipeline_ca_is_impo_ae7afa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["activo", "numero_800"], name="core_servic_activo_d8a537_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["center", "activo"], name="core_servic_center__66aa64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["fecha", "servicio_800"], name="core_call_r_fecha_960fab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["fecha", "telefono"], name="core_call_r_fecha_b2b83b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["-fecha", "-total_llamadas"],
                name="core_call_r_fecha_980b6e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["agent", "fecha"], name="core_call_r_agent_i_27010f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="callrecord",
            index=models.Index(
                fields=["call_type", "fecha"], name="core_call_r_call_ty_ee25fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="callrecord",
            unique_together={("fecha", "telefono", "servicio_800")},
        ),
    ]
