# Generated by Django 5.0.1 on 2026-01-25 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Asunto")),
                ("body", models.TextField(verbose_name="Contenido")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("critical", "Crítica"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje Interno",
                "verbose_name_plural": "Mensajes Internos",
                "db_table": "alerts_internal_message",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de archivo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de recepción"
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinatario de Mensaje",
                "verbose_name_plural": "Destinatarios de Mensajes",
                "db_table": "alerts_message_recipient",
            },
        ),
        migrations.CreateModel(
            name="AlertConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "condition",
                    models.JSONField(
                        help_text="Condición en formato JSON", verbose_name="Condición"
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Informativa"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("critical", "Crítica"),
                        ],
                        default="info",
                        max_length=10,
                        verbose_name="Prioridad",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "last_evaluated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Última evaluación"
                    ),
                ),
                (
                    "last_triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último disparo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Alerta",
                "verbose_name_plural": "Configuraciones de Alertas",
                "db_table": "alerts_alert_configuration",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_alert_active"),
                    models.Index(fields=["-created_at"], name="idx_alert_created"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "subscribed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de suscripción"
                    ),
                ),
                (
                    "alert_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="alerts.alertconfiguration",
                        verbose_name="Configuración de Alerta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Suscripción a Alerta",
                "verbose_name_plural": "Suscripciones a Alertas",
                "db_table": "alerts_alert_subscription",
            },
        ),
    ]
