# Generated by Django 5.0.1 on 2026-01-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Remitente",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_recipients",
                to="alerts.internalmessage",
                verbose_name="Mensaje",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_receipts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="internalmessage",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages",
                through="alerts.MessageRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Destinatarios",
            ),
        ),
        migrations.AddIndex(
            model_name="alertsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="idx_sub_user_active"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertsubscription",
            unique_together={("user", "alert_configuration")},
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(fields=["user", "read_at"], name="idx_rcpt_user_read"),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["user", "archived_at"], name="idx_rcpt_user_arch"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="internalmessage",
            index=models.Index(fields=["-created_at"], name="idx_msg_created"),
        ),
        migrations.AddIndex(
            model_name="internalmessage",
            index=models.Index(fields=["sender", "-created_at"], name="idx_msg_sender"),
        ),
        migrations.AddIndex(
            model_name="internalmessage",
            index=models.Index(fields=["priority"], name="idx_msg_priority"),
        ),
    ]
