# Generated by Django 5.0.1 on 2026-05-14 19:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_fase0_internal_mailbox'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalmailbox',
            name='owner',
            field=models.OneToOneField(help_text='Usuario dueño del buzón (1:1).', on_delete=django.db.models.deletion.CASCADE, related_name='mailbox', to=settings.AUTH_USER_MODEL, verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='mailboxmessage',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='None = mensaje del sistema.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('metric', models.CharField(help_text='Métrica evaluada (call_volume, avg_wait_time, sla_percentage…).', max_length=100, verbose_name='Métrica')),
                ('scope', models.JSONField(help_text='{"segment"?, "queue"?, "campaign"?}. Validado por RuleValidator.', verbose_name='Scope')),
                ('condition', models.JSONField(help_text='{"op": "> | < | >= | <= | ==", "threshold": N}.', verbose_name='Condición')),
                ('window_minutes', models.PositiveIntegerField(help_text='Ventana de evaluación en minutos.', verbose_name='Ventana (min)')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10, verbose_name='Severidad')),
                ('actions', models.JSONField(default=list, help_text='Lista de acciones a ejecutar cuando la regla se dispara.', verbose_name='Acciones')),
                ('cooldown_minutes', models.PositiveIntegerField(default=60, help_text='Minutos que deben pasar antes de que la regla se dispare de nuevo (CA-09).', verbose_name='Cooldown (min)')),
                ('status', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada')], default='active', max_length=10, verbose_name='Estado')),
                ('version', models.PositiveIntegerField(default=1, help_text='Incrementado en cada update (CA-05). Permite trazabilidad de cambios.', verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('actor', models.ForeignKey(help_text='Usuario que creó la regla.', on_delete=django.db.models.deletion.PROTECT, related_name='alert_rules', to=settings.AUTH_USER_MODEL, verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
                'db_table': 'alerts_alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200, verbose_name='Nombre regla (snapshot)')),
                ('metric', models.JSONField(verbose_name='Métrica (snapshot)')),
                ('scope', models.JSONField(verbose_name='Scope (snapshot)')),
                ('severity', models.CharField(max_length=10, verbose_name='Severidad')),
                ('state', models.CharField(choices=[('firing', 'Disparada'), ('acknowledged', 'Reconocida'), ('resolved', 'Resuelta'), ('closed', 'Cerrada')], default='firing', max_length=15, verbose_name='Estado')),
                ('fired_at', models.DateTimeField(verbose_name='Disparada en')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconocida en')),
                ('acknowledged_note', models.TextField(blank=True, help_text='UC_ALR_03 CA-02: nota libre. Máx 500 chars — validado en servicio.', verbose_name='Nota de reconocimiento')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resuelta en')),
                ('current_value', models.FloatField(blank=True, help_text='Valor de la métrica en el momento del query.', null=True, verbose_name='Valor actual')),
                ('threshold', models.FloatField(blank=True, help_text='Threshold de la condición en el momento del disparo.', null=True, verbose_name='Umbral (snapshot)')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Reconocida por')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='alerts.alertrule', verbose_name='Regla')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerts_alert',
                'ordering': ['-fired_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRuleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Versión')),
                ('snapshot', models.JSONField(help_text='Copia completa del AlertRule en el momento del cambio.', verbose_name='Snapshot')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Cambiado en')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_rule_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule', verbose_name='Regla')),
            ],
            options={
                'verbose_name': 'Historial de Regla',
                'verbose_name_plural': 'Historiales de Regla',
                'db_table': 'alerts_alert_rule_history',
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['actor'], name='idx_alr_actor'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['status', 'version'], name='idx_alr_status_ver'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['state', 'severity', '-fired_at'], name='idx_alert_state_sev'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['rule', '-fired_at'], name='idx_alert_rule'),
        ),
        migrations.AlterUniqueTogether(
            name='alertrulehistory',
            unique_together={('rule', 'version')},
        ),
    ]
