# Generated by Django 5.0.1 on 2026-05-14 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_fase3_prereq_alert_rule_and_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alertsubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='alerts.alertrule', verbose_name='Regla de Alerta'),
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='severity_filter',
            field=models.CharField(default='warning', help_text='Filtro de severidad mínima para notificar.', max_length=20),
        ),
        migrations.AddField(
            model_name='alertsubscription',
            name='state',
            field=models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('auto_paused', 'Auto-pausada')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='alertsubscription',
            name='alert_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='alerts.alertconfiguration', verbose_name='Configuración de Alerta (legacy)'),
        ),
        migrations.AlterField(
            model_name='alertsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa (legacy)'),
        ),
        migrations.AddIndex(
            model_name='alertsubscription',
            index=models.Index(fields=['user', 'state'], name='idx_sub_user_state'),
        ),
    ]
