# Generated by Django 5.0.1 on 2026-05-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_fase4_alertsubscription_canonical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailboxmessage',
            name='priority',
            field=models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('error', 'Error'), ('critical', 'Crítica')], default='info', max_length=10, verbose_name='Prioridad'),
        ),
    ]
