# Generated by Django 5.0.1 on 2026-05-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('username', models.CharField(db_column='cUsername', help_text='Username que se intentó usar', max_length=150, verbose_name='Username Intentado')),
                ('success', models.BooleanField(db_column='bExitoso', help_text='True si login fue exitoso', verbose_name='Exitoso')),
                ('ip_address', models.GenericIPAddressField(db_column='cIpAddress', help_text='IP desde donde se intentó el login', verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, db_column='cUserAgent', help_text='User agent del navegador', max_length=255, verbose_name='User Agent')),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'tbl_intentos_login',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('username', models.CharField(db_index=True, help_text='Username del usuario', max_length=150, unique=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Número de intentos fallidos')),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, help_text='Bloqueado hasta este timestamp (None = no bloqueado)', null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True, help_text='Timestamp del último intento')),
            ],
            options={
                'verbose_name': 'Login Lockout',
                'verbose_name_plural': 'Login Lockouts',
                'db_table': 'authentication_login_lockout',
                'ordering': ['-last_attempt_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('question', models.CharField(db_column='cPregunta', help_text='Texto de la pregunta de seguridad', max_length=255, unique=True, verbose_name='Pregunta')),
                ('is_active', models.BooleanField(db_column='bActiva', default=True, help_text='Si la pregunta está disponible para usar', verbose_name='Activa')),
                ('order', models.IntegerField(db_column='iOrden', default=0, help_text='Orden de presentación en UI', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Pregunta de Seguridad',
                'verbose_name_plural': 'Preguntas de Seguridad',
                'db_table': 'tbl_preguntas_seguridad',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='SessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('session_key', models.CharField(db_column='cSessionKey', help_text='Django session key', max_length=40, verbose_name='Session Key')),
                ('ip_address', models.GenericIPAddressField(db_column='cIpAddress', help_text='IP desde donde se hizo login', verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, db_column='cUserAgent', help_text='User agent del navegador', max_length=255, verbose_name='User Agent')),
                ('logout_at', models.DateTimeField(blank=True, db_column='dtLogout', help_text='Fecha y hora de logout', null=True, verbose_name='Logout')),
                ('is_active', models.BooleanField(db_column='bActiva', default=True, help_text='Si la sesión está activa', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Log de Sesión',
                'verbose_name_plural': 'Logs de Sesiones',
                'db_table': 'tbl_log_sesiones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indica si el registro está eliminado (delete lógico)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora en que se eliminó el registro', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('answer_hash', models.CharField(db_column='cHashRespuesta', help_text='Hash PBKDF2 de la respuesta normalizada', max_length=255, verbose_name='Hash Respuesta')),
            ],
            options={
                'verbose_name': 'Respuesta de Seguridad',
                'verbose_name_plural': 'Respuestas de Seguridad',
                'db_table': 'tbl_respuestas_seguridad',
            },
        ),
    ]
