# Generated by Django 5.0.1 on 2026-05-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='user',
            field=models.ForeignKey(blank=True, db_column='iIdUsuario', help_text='Usuario (null si no existe el username)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='loginlockout',
            index=models.Index(fields=['username', 'locked_until'], name='idx_username_locked'),
        ),
        migrations.AddIndex(
            model_name='loginlockout',
            index=models.Index(fields=['last_attempt_at'], name='idx_last_attempt'),
        ),
        migrations.AddIndex(
            model_name='securityquestion',
            index=models.Index(fields=['is_active', 'order'], name='idx_secq_active'),
        ),
        migrations.AddIndex(
            model_name='securityquestion',
            index=models.Index(fields=['is_deleted'], name='idx_secq_deleted'),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='sessionlog',
            name='user',
            field=models.ForeignKey(db_column='iIdUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='usersecurityanswer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='usersecurityanswer',
            name='question',
            field=models.ForeignKey(db_column='iIdPregunta', on_delete=django.db.models.deletion.PROTECT, to='authentication.securityquestion', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='usersecurityanswer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='usersecurityanswer',
            name='user',
            field=models.ForeignKey(db_column='iIdUsuario', on_delete=django.db.models.deletion.CASCADE, related_name='security_answers', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', '-created_at'], name='idx_login_username'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', '-created_at'], name='idx_login_ip'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['success', '-created_at'], name='idx_login_success'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_session_user'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['session_key'], name='idx_session_key'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['is_active'], name='idx_session_active'),
        ),
        migrations.AddIndex(
            model_name='sessionlog',
            index=models.Index(fields=['is_deleted'], name='idx_session_deleted'),
        ),
        migrations.AddIndex(
            model_name='usersecurityanswer',
            index=models.Index(fields=['user'], name='idx_secanswer_user'),
        ),
        migrations.AddIndex(
            model_name='usersecurityanswer',
            index=models.Index(fields=['is_deleted'], name='idx_secanswer_deleted'),
        ),
        migrations.AlterUniqueTogether(
            name='usersecurityanswer',
            unique_together={('user', 'question')},
        ),
    ]
