# Generated by Django 5.0.1 on 2026-05-15 18:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_fase2_blacklisted_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='expires_at',
            field=models.DateTimeField(db_index=True, help_text='Fecha de expiración original. Usada por el cron de purga.', verbose_name='Expira en'),
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='jti',
            field=models.CharField(help_text='Claim jti del token. UNIQUE para lookup O(1).', max_length=255, unique=True, verbose_name='JWT ID (jti)'),
        ),
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token_type',
            field=models.CharField(choices=[('ACCESS', 'Access token'), ('REFRESH', 'Refresh token')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='session',
            name='client_info',
            field=models.JSONField(blank=True, default=dict, help_text='Dispositivo, plataforma, etc. UC_AUTH_01 FA-03.', verbose_name='Info cliente'),
        ),
        migrations.AlterField(
            model_name='session',
            name='close_reason',
            field=models.CharField(blank=True, default='', help_text='USER_LOGOUT | SUPERSEDED | ADMIN_CLOSE | EXPIRED | USER_ELIMINATED', max_length=30, verbose_name='Razón de cierre'),
        ),
        migrations.AlterField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(db_index=True, help_text='started_at + 15 min (CNST-002). Se extiende con actividad.', verbose_name='Expira'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_activity_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Se actualiza en cada request autenticado (CNST-002).', verbose_name='Última actividad'),
        ),
        migrations.AlterField(
            model_name='session',
            name='scope',
            field=models.CharField(default='full', help_text="'full' normal | 'restricted' solo UC_AUTH_04+02 (FA-01).", max_length=20, verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID de la sesión. Expuesto en el response de login.', primary_key=True, serialize=False, verbose_name='Session ID'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Activa'), ('CLOSED', 'Cerrada'), ('EXPIRED', 'Expirada')], db_index=True, default='ACTIVE', help_text='ACTIVE | CLOSED | EXPIRED. BR-009: nunca DELETE.', max_length=10, verbose_name='Estado'),
        ),
    ]
