# Generated by Django 5.0.1 on 2026-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("excel", "Excel")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta del archivo exportado",
                        max_length=500,
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(
                        help_text="Total registros a exportar (max 100K CNST-007)"
                    ),
                ),
                (
                    "exported_records",
                    models.IntegerField(
                        default=0, help_text="Registros exportados (progreso)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="Inicio de la exportación", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="Fin de la exportación", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Mensaje de error si falla"),
                ),
            ],
            options={
                "verbose_name": "Export Job",
                "verbose_name_plural": "Export Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre descriptivo del reporte", max_length=200
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("calls", "Llamadas"),
                            ("users", "Usuarios"),
                            ("audit", "Auditoría"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "filters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Filtros aplicados al reporte (JSON)",
                    ),
                ),
                (
                    "total_records",
                    models.IntegerField(
                        default=0, help_text="Total de registros en el reporte"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
