# Generated by Django 5.0.1 on 2026-01-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="export_jobs",
                to="reports.report",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-created_at", "report_type"],
                name="reports_rep_created_500549_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["created_by", "status"], name="reports_rep_created_4bb467_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["report", "status"], name="reports_exp_report__43cbe3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(
                fields=["-created_at"], name="reports_exp_created_6d462c_idx"
            ),
        ),
    ]
