# Generated by Django 5.0.1 on 2026-05-14 20:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_scheduled_report_saved_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exportjob',
            name='reports_exp_report__43cbe3_idx',
        ),
        migrations.RenameIndex(
            model_name='exportjob',
            new_name='idx_expjob_created',
            old_name='reports_exp_created_6d462c_idx',
        ),
        migrations.AddField(
            model_name='exportjob',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Usuario que solicitó la exportación. Obligatorio para UC_RPT_04.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='byte_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bytes'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='cancellation_requested',
            field=models.BooleanField(default=False, help_text='True cuando se hace DELETE durante status=running.', verbose_name='Cancelación solicitada'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='error_code',
            field=models.CharField(blank=True, help_text='PERMISSION_REVOKED | TOO_LARGE | STORAGE_UNAVAILABLE | BD_TIMEOUT | …', max_length=50, null=True, verbose_name='Código de error'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='file_url',
            field=models.CharField(blank=True, help_text='URL con TTL 24h (CA-12).', max_length=2000, null=True, verbose_name='URL firmado'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='file_url_expires_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de expiración de file_url.', null=True, verbose_name='URL expira en'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='filters',
            field=models.JSONField(default=dict, verbose_name='Filtros'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='group_by',
            field=models.JSONField(default=list, verbose_name='Agrupar por'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='period',
            field=models.JSONField(default=dict, verbose_name='Período'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='progress_pct',
            field=models.PositiveSmallIntegerField(default=0, help_text='0..100.', verbose_name='Progreso (%)'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='report_type',
            field=models.CharField(blank=True, help_text='Enum: agent_performance, audit_export, call_summary, campaign_summary, ivr_navigation, queue_stats', max_length=50, null=True, verbose_name='Tipo de reporte'),
        ),
        migrations.AddField(
            model_name='exportjob',
            name='row_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Filas'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completado en'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='error_message',
            field=models.TextField(blank=True, help_text='Legacy. Usar error_code para UC_RPT_04.'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='exported_records',
            field=models.IntegerField(default=0, help_text='Legacy. Usar progress_pct para UC_RPT_04.'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ruta de archivo'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('pdf', 'PDF')], default='csv', max_length=10, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='report',
            field=models.ForeignKey(blank=True, help_text='FK legacy — null para jobs UC_RPT_04.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to='reports.report', verbose_name='Reporte legacy'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='status',
            field=models.CharField(choices=[('queued', 'En cola'), ('running', 'Ejecutando'), ('done', 'Completado'), ('failed', 'Fallido'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], db_index=True, default='queued', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='exportjob',
            name='total_records',
            field=models.IntegerField(blank=True, help_text='Legacy. Usar row_count para UC_RPT_04.', null=True),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['actor', 'status'], name='idx_expjob_actor_status'),
        ),
        migrations.AddIndex(
            model_name='exportjob',
            index=models.Index(fields=['status', 'file_url_expires_at'], name='idx_expjob_status_expiry'),
        ),
        migrations.AlterModelTable(
            name='exportjob',
            table='reports_exportjob',
        ),
    ]
