# Generated by Django 5.0.1 on 2026-05-14 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_fase3_exportjob_canonical'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledreport',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='Usuario que programó el reporte. Obligatorio para UC_RPT_07.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Actor'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='auto_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='cron_expr_legacy',
            field=models.CharField(blank=True, help_text='Legacy field — usar cron_expression.', max_length=50),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1..31 — solo para frequency=monthly (CA-03).', null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='day_of_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0=lunes … 6=domingo — solo para frequency=weekly (CA-02).', null=True),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='failure_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Fallos consecutivos. ≥3 → auto_paused (CA-10).'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='filters',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('json', 'JSON'), ('pdf', 'PDF')], default='csv', max_length=10),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('cron', 'Expresión cron personalizada')], default='daily', max_length=15),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='group_by',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='last_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_source', to='reports.exportjob'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='report_type',
            field=models.CharField(blank=True, default='', help_text='Mismo enum que ExportJob.report_type.', max_length=50, verbose_name='Tipo de reporte'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='run_at_hour',
            field=models.PositiveSmallIntegerField(default=6, help_text='Hora local de ejecución (0..23).'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='run_at_minute',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='status',
            field=models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('auto_paused', 'Auto-pausado'), ('deleted', 'Eliminado')], db_index=True, default='active', max_length=15),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(help_text='Legacy — usar actor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_reports_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="'0 6 * * 1' — solo para frequency=cron (CA-04).", max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Legacy — usar status.'),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='next_run_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledreport',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_runs', to='reports.report', verbose_name='Reporte legacy'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['actor', 'status'], name='idx_schedrpt_actor_status'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['next_run_at', 'status'], name='idx_schedrpt_next_run'),
        ),
        migrations.AlterModelTable(
            name='scheduledreport',
            table='reports_scheduledreport',
        ),
    ]
