# Generated by Django 5.0.1 on 2026-05-14 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_fase4_scheduledreport_canonical'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(blank=True, help_text='Tipo de reporte al que aplica (CA-09: default único por tipo).', max_length=50)),
                ('applies_to', models.JSONField(default=list, help_text='Lista de report_types a los que aplica este filtro.')),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False, help_text='CA-09: único is_default por report_type por usuario.')),
                ('is_valid', models.BooleanField(default=True, help_text='CA-10: False si el usuario pierde el segmento requerido.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Saved Filter',
                'verbose_name_plural': 'Saved Filters',
                'db_table': 'reports_savedfilter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='savedview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedview',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='UC_RPT_10 canonical actor. Null para registros legacy.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedview',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='savedview',
            name='is_available',
            field=models.BooleanField(default=True, help_text='CA-08: False si alguna columna fue deprecada.'),
        ),
        migrations.AddField(
            model_name='savedview',
            name='is_default',
            field=models.BooleanField(default=False, help_text='CA-05: único is_default por report_type por usuario.'),
        ),
        migrations.AddField(
            model_name='savedview',
            name='report_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='savedview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='columns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Legacy — usar actor.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_views_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='filters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedview',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_views', to='reports.report', verbose_name='Reporte legacy'),
        ),
        migrations.AddIndex(
            model_name='savedview',
            index=models.Index(fields=['actor', 'report_type'], name='idx_savedview_actor_type'),
        ),
        migrations.AlterModelTable(
            name='savedview',
            table='reports_savedview',
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_saved_filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['actor', 'report_type'], name='idx_savedfilter_actor_type'),
        ),
    ]
