# Generated by Django 5.0.1 on 2026-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="LOGIN, LOGOUT, CREATE, UPDATE, DELETE, etc",
                        max_length=50,
                        verbose_name="Accion",
                    ),
                ),
                (
                    "resource",
                    models.CharField(
                        help_text="Recurso afectado",
                        max_length=200,
                        verbose_name="Recurso",
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "Exito"), ("FAILURE", "Fallo")],
                        max_length=20,
                        verbose_name="Resultado",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha/Hora"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "details",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Detalles adicionales"
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Auditoria",
                "verbose_name_plural": "Logs Auditoria",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
