# Generated by Django 5.0.1 on 2026-01-25 08:23

import apps.users.models
import apps.users.validators
import apps.utils.validators
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono del usuario (formato: +1234567890 o 123-456-7890)",
                        max_length=20,
                        null=True,
                        validators=[apps.utils.validators.validate_phone_number],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CEO", "CEO"),
                            ("CTO", "CTO"),
                            ("CFO", "CFO"),
                            ("MANAGER", "Manager"),
                            ("SUPERVISOR", "Supervisor"),
                            ("TEAM_LEAD", "Team Lead"),
                            ("SENIOR_DEV", "Senior Developer"),
                            ("DEVELOPER", "Developer"),
                            ("JUNIOR_DEV", "Junior Developer"),
                            ("ANALYST", "Analyst"),
                            ("SPECIALIST", "Specialist"),
                            ("COORDINATOR", "Coordinator"),
                            ("ASSISTANT", "Assistant"),
                            ("INTERN", "Intern"),
                        ],
                        help_text="Cargo o posición del usuario en la organización",
                        max_length=100,
                        null=True,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default=None,
                        help_text="Imagen de perfil del usuario (max 2MB, formatos: jpg, png, gif)",
                        max_length=255,
                        null=True,
                        upload_to=apps.users.models.user_avatar_path,
                        validators=[apps.users.validators.validate_avatar_file],
                        verbose_name="Avatar",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users",
                "ordering": ["username"],
            },
        ),
        migrations.CreateModel(
            name="SessionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última actualización",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP desde donde se conectó",
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        help_text="Información del navegador/cliente",
                        max_length=255,
                        verbose_name="User Agent",
                    ),
                ),
                (
                    "login_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de login",
                        verbose_name="Login",
                    ),
                ),
                (
                    "logout_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora de logout",
                        null=True,
                        verbose_name="Logout",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True si la sesión sigue activa",
                        verbose_name="Sesión Activa",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Sesión",
                "verbose_name_plural": "Historial de Sesiones",
                "db_table": "session_history",
                "ordering": ["-login_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última actualización",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Descripción breve del usuario",
                        null=True,
                        verbose_name="Biografía",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("IT", "Tecnología (IT)"),
                            ("HR", "Recursos Humanos"),
                            ("SALES", "Ventas"),
                            ("MARKETING", "Marketing"),
                            ("FINANCE", "Finanzas"),
                            ("OPERATIONS", "Operaciones"),
                            ("CUSTOMER_SERVICE", "Servicio al Cliente"),
                            ("ADMIN", "Administración"),
                        ],
                        help_text="Departamento al que pertenece",
                        max_length=100,
                        null=True,
                        verbose_name="Departamento",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
                "db_table": "user_profiles",
            },
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación",
                        verbose_name="Creado",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Fecha y hora de última actualización",
                        verbose_name="Actualizado",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("es", "Español"), ("en", "English")],
                        default="es",
                        help_text="Idioma de la interfaz",
                        max_length=10,
                        verbose_name="Idioma",
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Habilitar/deshabilitar notificaciones",
                        verbose_name="Notificaciones Habilitadas",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Usuario",
                "verbose_name_plural": "Configuraciones de Usuario",
                "db_table": "user_settings",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_username_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_idx"),
        ),
        migrations.AddIndex(
            model_name="sessionhistory",
            index=models.Index(
                fields=["user", "-login_at"], name="sessions_user_login_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionhistory",
            index=models.Index(
                fields=["is_active", "-login_at"], name="sessions_active_idx"
            ),
        ),
    ]
