# Generated by Django 5.0.1 on 2026-05-15 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_fase2_user_admin_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_hash',
            field=models.CharField(help_text='Hash bcrypt de la contraseña. Nunca en texto plano.', max_length=128, verbose_name='Hash de contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, help_text='UC_USR_01 PASO 10.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, help_text='True al crear la cuenta. UC_AUTH_01 FA-01: fuerza cambio de contraseña.', verbose_name='Primer login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='UC_AUTH_01 paso 14: actualizado en cada login exitoso.', null=True, verbose_name='Último login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified_at',
            field=models.DateTimeField(blank=True, help_text='UC_USR_03 PASO 8.', null=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_expires_at',
            field=models.DateTimeField(blank=True, help_text='UC_AUTH_01 FA-02: aviso cuando password_expires_at - now() < ventana.', null=True, verbose_name='Contraseña expira'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('BLOCKED', 'Bloqueado'), ('ELIMINATED', 'Eliminado')], db_index=True, default='ACTIVE', help_text='Estado canónico del usuario. ELIMINATED = baja lógica definitiva.', max_length=10, verbose_name='Estado'),
        ),
    ]
