# Generated by Django 5.0.1 on 2026-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "config_name",
                    models.CharField(
                        help_text="Nombre del dashboard",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del dashboard",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con configuración de layout: columns, widgets, etc.",
                        verbose_name="Configuración de Layout",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Si es el dashboard por defecto del usuario",
                        verbose_name="Es Default",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Si el dashboard puede ser visto por otros usuarios",
                        verbose_name="Es Público",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Configuración de Dashboard",
                "verbose_name_plural": "Configuraciones de Dashboard",
                "db_table": "dashboard_config",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Indica si el registro está eliminado (delete lógico)",
                        verbose_name="Eliminado",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha y hora en que se eliminó el registro",
                        null=True,
                        verbose_name="Eliminado en",
                    ),
                ),
                (
                    "filter_name",
                    models.CharField(
                        help_text="Nombre descriptivo del filtro",
                        max_length=100,
                        verbose_name="Nombre del Filtro",
                    ),
                ),
                (
                    "filter_type",
                    models.CharField(
                        choices=[
                            ("CALLS", "Llamadas"),
                            ("TRANSFERS", "Transferencias"),
                            ("ABANDONED", "Abandonadas"),
                            ("CLIENTS", "Clientes"),
                            ("AGENTS", "Agentes"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        help_text="Tipo de filtro para categorización",
                        max_length=20,
                        verbose_name="Tipo de Filtro",
                    ),
                ),
                (
                    "filter_config",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con configuración: date_from, date_to, did, client_id, etc.",
                        verbose_name="Configuración del Filtro",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Si el filtro puede ser usado por otros usuarios",
                        verbose_name="Es Público",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Filtro Guardado",
                "verbose_name_plural": "Filtros Guardados",
                "db_table": "saved_filter",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDashboardPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Claro"),
                            ("dark", "Oscuro"),
                            ("auto", "Automático"),
                        ],
                        default="light",
                        help_text="Tema visual de la interfaz",
                        max_length=10,
                        verbose_name="Tema",
                    ),
                ),
                (
                    "refresh_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Si el refresh automático de widgets está habilitado",
                        verbose_name="Refresh Habilitado",
                    ),
                ),
                (
                    "refresh_interval_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="Intervalo de refresh global en segundos (min: 60, max: 3600)",
                        verbose_name="Intervalo de Refresh Global",
                    ),
                ),
                (
                    "show_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Si se muestran notificaciones de alertas",
                        verbose_name="Mostrar Notificaciones",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con preferencias: language, timezone, date_format, etc.",
                        verbose_name="Preferencias Adicionales",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Preferencia de Dashboard",
                "verbose_name_plural": "Preferencias de Dashboard",
                "db_table": "user_dashboard_preference",
            },
        ),
        migrations.CreateModel(
            name="WidgetConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("CALLS_CHART", "Gráfico de Llamadas"),
                            ("TRANSFERS_CHART", "Gráfico de Transferencias"),
                            ("ABANDONMENTS_CHART", "Gráfico de Abandonos"),
                            ("TOP_CLIENTS", "Top Clientes"),
                            ("METRICS_SUMMARY", "Resumen de Métricas"),
                            ("HOURLY_STATS", "Estadísticas por Hora"),
                            ("AGENT_PERFORMANCE", "Rendimiento de Agentes"),
                            ("SLA_MONITOR", "Monitor de SLA"),
                        ],
                        help_text="Tipo de visualización del widget",
                        max_length=50,
                        verbose_name="Tipo de Widget",
                    ),
                ),
                (
                    "widget_name",
                    models.CharField(
                        help_text="Nombre personalizado para el widget",
                        max_length=100,
                        verbose_name="Nombre del Widget",
                    ),
                ),
                (
                    "position_x",
                    models.IntegerField(
                        default=0,
                        help_text="Posición horizontal en grid (0-11)",
                        verbose_name="Posición X",
                    ),
                ),
                (
                    "position_y",
                    models.IntegerField(
                        default=0,
                        help_text="Posición vertical en grid",
                        verbose_name="Posición Y",
                    ),
                ),
                (
                    "width",
                    models.IntegerField(
                        default=6,
                        help_text="Ancho en columnas de grid (1-12)",
                        verbose_name="Ancho",
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        default=4,
                        help_text="Alto en unidades de grid",
                        verbose_name="Alto",
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        default=dict,
                        help_text="JSON con configuración: chart_type, metrics, filters, etc.",
                        verbose_name="Configuración del Widget",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(
                        default=True,
                        help_text="Si el widget está visible en el dashboard",
                        verbose_name="Visible",
                    ),
                ),
                (
                    "refresh_interval_seconds",
                    models.IntegerField(
                        default=300,
                        help_text="Intervalo de actualización automática en segundos (min: 60, max: 3600)",
                        verbose_name="Intervalo de Actualización",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado el"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado el"),
                ),
            ],
            options={
                "verbose_name": "Configuración de Widget",
                "verbose_name_plural": "Configuraciones de Widgets",
                "db_table": "widget_config",
                "ordering": ["position_y", "position_x"],
            },
        ),
    ]
