# Generated by Django 5.0.1 on 2026-05-05 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardconfig',
            name='user',
            field=models.ForeignKey(help_text='Usuario propietario del dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='savedfilter',
            name='user',
            field=models.ForeignKey(help_text='Usuario propietario del filtro', on_delete=django.db.models.deletion.CASCADE, related_name='saved_filters', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='userdashboardpreference',
            name='default_dashboard',
            field=models.ForeignKey(blank=True, help_text='Dashboard que se carga por defecto al entrar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_default', to='dashboard.dashboardconfig', verbose_name='Dashboard por Defecto'),
        ),
        migrations.AddField(
            model_name='userdashboardpreference',
            name='user',
            field=models.OneToOneField(help_text='Usuario propietario de las preferencias', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='dashboard',
            field=models.ForeignKey(help_text='Dashboard al que pertenece el widget', on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.dashboardconfig', verbose_name='Dashboard'),
        ),
        migrations.AddIndex(
            model_name='dashboardconfig',
            index=models.Index(fields=['user', '-updated_at'], name='dashboard_c_user_id_9ca60c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardconfig',
            index=models.Index(fields=['is_default', 'user'], name='dashboard_c_is_defa_c33c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardconfig',
            index=models.Index(fields=['is_public'], name='dashboard_c_is_publ_974407_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardconfig',
            index=models.Index(fields=['-created_at'], name='dashboard_c_created_84b51d_idx'),
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['user', '-updated_at'], name='saved_filte_user_id_9b1fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['filter_type'], name='saved_filte_filter__eed669_idx'),
        ),
        migrations.AddIndex(
            model_name='savedfilter',
            index=models.Index(fields=['is_public'], name='saved_filte_is_publ_a93952_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetconfig',
            index=models.Index(fields=['dashboard', 'position_y', 'position_x'], name='widget_conf_dashboa_475c07_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetconfig',
            index=models.Index(fields=['widget_type'], name='widget_conf_widget__85e912_idx'),
        ),
        migrations.AddIndex(
            model_name='widgetconfig',
            index=models.Index(fields=['is_visible'], name='widget_conf_is_visi_960027_idx'),
        ),
    ]
