# Generated by Django 5.0.1 on 2026-05-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblTempPruebaIvr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Temp Prueba IVR',
                'verbose_name_plural': 'Temp Prueba IVR',
                'db_table': 'tbl_temp_prueba_ivr',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
