# Generated by Django 5.0.1 on 2026-01-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(help_text="Fecha de las llamadas")),
                (
                    "telefono",
                    models.CharField(help_text="Numero telefonico", max_length=20),
                ),
                (
                    "servicio_800",
                    models.CharField(help_text="Numero servicio 800", max_length=20),
                ),
                (
                    "total_llamadas",
                    models.IntegerField(default=0, help_text="Total llamadas"),
                ),
                (
                    "llamadas_contestadas",
                    models.IntegerField(default=0, help_text="Llamadas contestadas"),
                ),
                (
                    "llamadas_abandonadas",
                    models.IntegerField(default=0, help_text="Llamadas abandonadas"),
                ),
                ("created_at", models.DateTimeField(help_text="Timestamp creacion")),
            ],
            options={
                "verbose_name": "Call Log Legacy",
                "verbose_name_plural": "Call Logs Legacy",
                "db_table": "call_logs",
                "ordering": ["-fecha"],
                "managed": False,
            },
        ),
    ]
