# Generated by Django 5.0.1 on 2026-05-05 23:23

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, validators=[apps.core.validators.validate_module_name], verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('icon', models.CharField(blank=True, max_length=200, verbose_name='Icono')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='access.module', verbose_name='Modulo padre')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'db_table': 'access_module',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=50, unique=True, validators=[apps.core.validators.validate_function_code], verbose_name='Codigo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='access.module', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones',
                'db_table': 'access_function',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='access.function', verbose_name='Funcion')),
            ],
            options={
                'verbose_name': 'Permiso de usuario',
                'verbose_name_plural': 'Permisos de usuario',
                'db_table': 'access_user_permission',
            },
        ),
    ]
