# Generated by Django 5.0.1 on 2026-01-25 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userfunctionassignment",
            name="assigned_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="functions_assigned_by_me",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Asignado por",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionassignment",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assignments",
                to="access.function",
                verbose_name="Funcion",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionassignment",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="functions_revoked_by_me",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revocada por",
            ),
        ),
        migrations.AddField(
            model_name="userfunctionassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddField(
            model_name="usermoduleaccess",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_accesses_granted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Otorgado por",
            ),
        ),
        migrations.AddField(
            model_name="usermoduleaccess",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_accesses",
                to="access.module",
                verbose_name="Módulo",
            ),
        ),
        migrations.AddField(
            model_name="usermoduleaccess",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_accesses_revoked",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Revocado por",
            ),
        ),
        migrations.AddField(
            model_name="usermoduleaccess",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_accesses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["parent", "is_active"], name="modules_parent__1233a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["code", "is_active"], name="modules_code_b8c894_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfunctionassignment",
            index=models.Index(
                fields=["user", "is_active"], name="ufunc_user_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfunctionassignment",
            index=models.Index(
                fields=["function", "is_active"], name="ufunc_func_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfunctionassignment",
            index=models.Index(fields=["is_active"], name="ufunc_active_idx"),
        ),
        migrations.AddIndex(
            model_name="userfunctionassignment",
            index=models.Index(fields=["-assigned_at"], name="ufunc_assigned_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userfunctionassignment",
            unique_together={("user", "function")},
        ),
        migrations.AddIndex(
            model_name="usermoduleaccess",
            index=models.Index(
                fields=["user", "is_active"], name="user_module_user_id_65b0ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usermoduleaccess",
            index=models.Index(
                fields=["module", "is_active"], name="user_module_module__45c97a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usermoduleaccess",
            unique_together={("user", "module")},
        ),
    ]
