# Generated by Django 5.0.1 on 2026-05-08 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='permission_django',
            field=models.CharField(blank=True, help_text='Formato: app.accion. Ej: reports.view, dashboard.export', max_length=100, unique=True, verbose_name='Namespace Django'),
        ),
        migrations.AddField(
            model_name='function',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='function',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(help_text='Identificador unico. Ej: SUPERVISOR_IVR', max_length=50, unique=True, verbose_name='Codigo')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('functions', models.ManyToManyField(blank=True, related_name='access_groups', to='access.function', verbose_name='Funciones')),
            ],
            options={
                'verbose_name': 'Grupo de acceso',
                'verbose_name_plural': 'Grupos de acceso',
                'db_table': 'access_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExceptionalPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.TextField(help_text='Minimo 50 caracteres explicando la necesidad.', verbose_name='Justificacion')),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='Estado')),
                ('valid_from', models.DateTimeField(verbose_name='Valido desde')),
                ('valid_until', models.DateTimeField(verbose_name='Valido hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_grants', to='access.function', verbose_name='Funcion')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_permissions_otorgados', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptional_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Permiso excepcional',
                'verbose_name_plural': 'Permisos excepcionales',
                'db_table': 'access_exceptional_permission',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeparationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la regla')),
                ('justification', models.TextField(help_text='Razon de negocio por la que estas funciones son incompatibles.', verbose_name='Justificacion')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20, verbose_name='Estado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('function_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_rules_as_a', to='access.function', verbose_name='Funcion A')),
                ('function_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separation_rules_as_b', to='access.function', verbose_name='Funcion B')),
            ],
            options={
                'verbose_name': 'Regla de separacion',
                'verbose_name_plural': 'Reglas de separacion',
                'db_table': 'access_separation_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserAccessGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('access_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='access.accessgroup', verbose_name='Grupo de acceso')),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access_groups', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Membresia de grupo',
                'verbose_name_plural': 'Membresias de grupo',
                'db_table': 'access_user_group',
            },
        ),
        migrations.CreateModel(
            name='UserFunctionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='Razon de la asignacion (opcional).', max_length=255, verbose_name='Motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Asignada en')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='function_assignments_granted', to=settings.AUTH_USER_MODEL, verbose_name='Asignada por')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='access.function', verbose_name='Funcion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignacion de funcion',
                'verbose_name_plural': 'Asignaciones de funcion',
                'db_table': 'access_user_function_assignment',
            },
        ),
        migrations.CreateModel(
            name='UserModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Otorgado en')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revocado en')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_accesses_granted', to=settings.AUTH_USER_MODEL, verbose_name='Otorgado por')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='access.module', verbose_name='Modulo')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_accesses_revoked', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso a modulo',
                'verbose_name_plural': 'Accesos a modulos',
                'db_table': 'access_user_module_access',
            },
        ),
        migrations.AddConstraint(
            model_name='separationrule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('function_a', 'function_b'), name='unique_separation_pair_active'),
        ),
        migrations.AlterUniqueTogether(
            name='useraccessgroup',
            unique_together={('user', 'access_group')},
        ),
        migrations.AlterUniqueTogether(
            name='userfunctionassignment',
            unique_together={('user', 'function')},
        ),
        migrations.AlterUniqueTogether(
            name='usermoduleaccess',
            unique_together={('user', 'module')},
        ),
    ]
