"""
Migration 0008 — STD_008 FASE 2: related_names SeparationRule + model field cleanups.

Cambio principal (STD_008 §3.3):
  AlterField functions_set_a: related_name sod_rules_as_set_a → separation_rules_as_set_a
  AlterField functions_set_b: related_name sod_rules_as_set_b → separation_rules_as_set_b

  Los related_names son accessors Python del ORM (fn.separation_rules_as_set_a.all()).
  AlterField en ManyToManyField NO modifica las tablas intermedias de BD:
    access_separation_rule_functions_set_a — sin cambios de esquema
    access_separation_rule_functions_set_b — sin cambios de esquema

Cambios adicionales (pre-existing pending — help_text/verbose_name sin migración):
  SeparationRule: code, created_by, description, name (help_text/verbose_name)
  SeparationRule: AlterModelOptions (ordering, verbose_name_plural)
  AccessGroup: is_predefined, retired_at (help_text actualizado)
  Function: menu_action/domain/icon/label_en/label_es/order/section/visible (verbose_name simplificado)
  MenuItem: id (auto BigAutoField)
  UserFunctionAssignment: expires_at, is_active, reason, revoke_reason (help_text)

  Estos cambios estaban pendientes porque los modelos de FASE 2 agregaron
  help_text y verbose_name sin generar la migración correspondiente.

Fuente: PLAN-IMPL-STD008-SOD-FASES-20260513 FASE 2
Hallazgo H-002: migraciones pendientes preexistentes en el app access.
"""
# Generated by Django 5.0.1 on 2026-05-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_fase2_access_group_and_function_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='separationrule',
            options={'ordering': ['code'], 'verbose_name': 'Regla SoD', 'verbose_name_plural': 'Reglas SoD'},
        ),
        migrations.AlterField(
            model_name='accessgroup',
            name='is_predefined',
            field=models.BooleanField(db_index=True, default=False, help_text='True para los 10 AGRs del catálogo v5.4.0. UC_PERM_05 CA-07: inmutables.', verbose_name='Predefinido'),
        ),
        migrations.AlterField(
            model_name='accessgroup',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Retirado en'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_action',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_domain',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Dominio'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_icon',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Icono'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_label_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Label EN'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_label_es',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Label ES'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Orden menú'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_section',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='function',
            name='menu_visible',
            field=models.BooleanField(default=False, verbose_name='Visible en menú'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='code',
            field=models.CharField(help_text='Identificador canónico. Ej: SOD-001. Fuente: modelo-rbac-iact.rst v5.4.0.', max_length=20, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separation_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='description',
            field=models.TextField(blank=True, help_text='Razon de negocio por la que estos conjuntos son incompatibles.', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='functions_set_a',
            field=models.ManyToManyField(blank=True, help_text='Funciones del primer conjunto en conflicto (ej: Pipeline).', related_name='separation_rules_as_set_a', to='access.function', verbose_name='Conjunto A'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='functions_set_b',
            field=models.ManyToManyField(blank=True, help_text='Funciones del segundo conjunto en conflicto (ej: Auditoria).', related_name='separation_rules_as_set_b', to='access.function', verbose_name='Conjunto B'),
        ),
        migrations.AlterField(
            model_name='separationrule',
            name='name',
            field=models.CharField(help_text='Nombre legible. Ej: pipeline_audit_separation.', max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='userfunctionassignment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Nullable: si es None la asignación no expira. UC_PERM_07 CA-06: expired assignment no cuenta.', null=True, verbose_name='Expira en'),
        ),
        migrations.AlterField(
            model_name='userfunctionassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='True cuando state=ACTIVE. Sincronizado automáticamente.', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='userfunctionassignment',
            name='reason',
            field=models.CharField(blank=True, help_text='Razón de la asignación (opcional).', max_length=255, verbose_name='Motivo de asignacion'),
        ),
        migrations.AlterField(
            model_name='userfunctionassignment',
            name='revoke_reason',
            field=models.CharField(blank=True, help_text='UC_ACC_02: revoke_reason obligatorio al revocar.', max_length=500, verbose_name='Motivo de revocacion'),
        ),
    ]
