# Generated by Django 5.0.1 on 2026-05-14 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_std008_fase2_related_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptionalpermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Obligatorio (CA-04). Bounds: NOW()+1h ≤ x ≤ NOW()+30d (CA-03).', null=True, verbose_name='Expira en'),
        ),
        migrations.AddField(
            model_name='exceptionalpermission',
            name='granted_at',
            field=models.DateTimeField(blank=True, help_text='NOW() en el momento del grant.', null=True, verbose_name='Otorgado en'),
        ),
        migrations.AddField(
            model_name='exceptionalpermission',
            name='revoke_reason',
            field=models.TextField(blank=True, help_text='UC_PERM_04 CA-06: obligatorio ≥ 20 chars.', verbose_name='Motivo de revocación'),
        ),
        migrations.AddField(
            model_name='exceptionalpermission',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp de revocación anticipada (UC_PERM_04 CA-02).', null=True, verbose_name='Revocado en'),
        ),
        migrations.AddField(
            model_name='exceptionalpermission',
            name='revoked_by',
            field=models.ForeignKey(blank=True, help_text='Diferencia con EXPIRED: revoked_by != NULL (CA-02).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exceptional_permissions_revocados', to=settings.AUTH_USER_MODEL, verbose_name='Revocado por'),
        ),
        migrations.AddField(
            model_name='exceptionalpermission',
            name='ticket_reference',
            field=models.CharField(blank=True, help_text='TKT-NNNNN — requerido si política REQUIRE_TICKET=true (CA-11).', max_length=100, null=True, verbose_name='Referencia de ticket'),
        ),
        migrations.AlterField(
            model_name='exceptionalpermission',
            name='justification',
            field=models.TextField(help_text='Mínimo 20 caracteres explicando la necesidad (uc-acc-08 CA-02).', verbose_name='Justificacion'),
        ),
        migrations.AlterField(
            model_name='exceptionalpermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('active', 'ACTIVE'), ('expired', 'EXPIRED'), ('revoked', 'REVOKED')], db_index=True, default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='exceptionalpermission',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Legacy: usar granted_at para UC_ACC_08.', null=True, verbose_name='Valido desde (legacy)'),
        ),
        migrations.AlterField(
            model_name='exceptionalpermission',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Legacy: usar expires_at para UC_ACC_08.', null=True, verbose_name='Valido hasta (legacy)'),
        ),
        migrations.AddIndex(
            model_name='exceptionalpermission',
            index=models.Index(fields=['user', 'status'], name='idx_excperm_user_status'),
        ),
        migrations.AddIndex(
            model_name='exceptionalpermission',
            index=models.Index(fields=['expires_at', 'status'], name='idx_excperm_expires'),
        ),
    ]
